version: 2
registries:
  # setup the public registry
  public:
    type: npm-registry
    url: https://registry.npmjs.org/
    token: ${{ secrets.DEPENDABOT_NULL_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
